### ISSUE TITLE
[Question] Plans to support Dove after move-build lands?

### ISSUE THREAD

**Issue by villesundell** [pontem-network/move-tools#97]
Hello!
Do you plan to develop and support Dove (with Diem) after move-build lands (https://github.com/diem/diem/pull/8775)?

It would be great to have only one build system for all the MoveVM platforms, so as a developer I would hope that either:
 *  Pontem would switch to move-build, or
 *  Pontem would continue supporting Diem :slightly_smiling_face:

**Comment by borispovod** [comment]
Hi @villesundell ,

Thank you for your question. 

The Pontem network goal is to be compatible with Diem, at least from smart contracts developers perspective. But at the same time, we are a less regulated network than Diem. Because of it we could have situations when we need our own compiler. 
For example, we are now discussing development of our own macro system that will help us save compatibility with Diem and Move compiler and at the same time give users access to regulated functions in Diem (those functions which require treasury signature or diem root signature in Diem Standard Library).

So, for now, we are still going to develop and support Dove to cover our needs.

**Comment by villesundell** [comment]
Thank you @borispovod, glad to hear Dove supports Diem in the future too, that means I can continue using that with TaoHe :slightly_smiling_face: Dove is a great build system, thank you for developing it! :heart:
